/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GradingRouteImport } from './routes/grading'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/collection/index'
import { Route as CollectionPokemonRouteImport } from './routes/collection/pokemon'
import { Route as CollectionOnepieceRouteImport } from './routes/collection/onepiece'
import { Route as ApiPublicEbayDeletionRouteImport } from './routes/api.public.ebay.deletion'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GradingRoute = GradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionPokemonRoute = CollectionPokemonRouteImport.update({
  id: '/collection/pokemon',
  path: '/collection/pokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionOnepieceRoute = CollectionOnepieceRouteImport.update({
  id: '/collection/onepiece',
  path: '/collection/onepiece',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEbayDeletionRoute = ApiPublicEbayDeletionRouteImport.update({
  id: '/api/public/ebay/deletion',
  path: '/api/public/ebay/deletion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/transactions': typeof TransactionsRoute
  '/collection/onepiece': typeof CollectionOnepieceRoute
  '/collection/pokemon': typeof CollectionPokemonRoute
  '/collection/': typeof CollectionIndexRoute
  '/api/public/ebay/deletion': typeof ApiPublicEbayDeletionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/transactions': typeof TransactionsRoute
  '/collection/onepiece': typeof CollectionOnepieceRoute
  '/collection/pokemon': typeof CollectionPokemonRoute
  '/collection': typeof CollectionIndexRoute
  '/api/public/ebay/deletion': typeof ApiPublicEbayDeletionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/transactions': typeof TransactionsRoute
  '/collection/onepiece': typeof CollectionOnepieceRoute
  '/collection/pokemon': typeof CollectionPokemonRoute
  '/collection/': typeof CollectionIndexRoute
  '/api/public/ebay/deletion': typeof ApiPublicEbayDeletionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/grading'
    | '/login'
    | '/search'
    | '/transactions'
    | '/collection/onepiece'
    | '/collection/pokemon'
    | '/collection/'
    | '/api/public/ebay/deletion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/grading'
    | '/login'
    | '/search'
    | '/transactions'
    | '/collection/onepiece'
    | '/collection/pokemon'
    | '/collection'
    | '/api/public/ebay/deletion'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/grading'
    | '/login'
    | '/search'
    | '/transactions'
    | '/collection/onepiece'
    | '/collection/pokemon'
    | '/collection/'
    | '/api/public/ebay/deletion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  GradingRoute: typeof GradingRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  TransactionsRoute: typeof TransactionsRoute
  CollectionOnepieceRoute: typeof CollectionOnepieceRoute
  CollectionPokemonRoute: typeof CollectionPokemonRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  ApiPublicEbayDeletionRoute: typeof ApiPublicEbayDeletionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grading': {
      id: '/grading'
      path: '/grading'
      fullPath: '/grading'
      preLoaderRoute: typeof GradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/pokemon': {
      id: '/collection/pokemon'
      path: '/collection/pokemon'
      fullPath: '/collection/pokemon'
      preLoaderRoute: typeof CollectionPokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/onepiece': {
      id: '/collection/onepiece'
      path: '/collection/onepiece'
      fullPath: '/collection/onepiece'
      preLoaderRoute: typeof CollectionOnepieceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ebay/deletion': {
      id: '/api/public/ebay/deletion'
      path: '/api/public/ebay/deletion'
      fullPath: '/api/public/ebay/deletion'
      preLoaderRoute: typeof ApiPublicEbayDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  GradingRoute: GradingRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  TransactionsRoute: TransactionsRoute,
  CollectionOnepieceRoute: CollectionOnepieceRoute,
  CollectionPokemonRoute: CollectionPokemonRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  ApiPublicEbayDeletionRoute: ApiPublicEbayDeletionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
